[package]
name = "cli_select"
version = "0.1.0"
edition = "2018"
author = "Pascal Frank"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"